### ISSUE TITLE
Accesion number not created for new strain page

### ISSUE THREAD

**Issue by Jguzman210** [microbialphenotypes/OMPwiki#1]
URL for page:
http://microbialphenotypes.org/wiki/index.php/Escherichia_coli_K-12_JF556

**Comment by dsiegele** [comment]
This issue was discussed in the OMP call on 2016-03-10. I realized that I had forgotten that the "Create a new strain page" form is located in the special pages. I added a link to the correct page on the "Create a New Page" page in the wiki.
