### ISSUE TITLE
S. pombe strains are showing up in E. coli annotations

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMPwiki#11]
http://microbialphenotypes.org/wiki/index.php/OMP_ST:941_!_Escherichia_coli_K-12_JW0452

For example: row annotation OMP_AN:702. 
This happens in other strains as well.

**Comment by jimhu-tamu** [comment]
Should be fixed, at least on that page. Try resaving the page if it still looks like the relative annotation links are bad.

**Comment by kylliechang** [comment]
That page was fixed, but the other pages I've worked on still has that problem.

**Comment by jimhu-tamu** [comment]
Not clear if this is still a problem on other pages.
