### ISSUE TITLE
Problem creating a new strain page 

### ISSUE THREAD

**Issue by KristenKC** [microbialphenotypes/OMPwiki#9]
When I try to create a new strain page (by using the link at the bottom of this post), I click submit at the bottom of the page but the page does not load after that and the strain has not been added to the ontology. 

http://microbialphenotypes.org/wiki/index.php/Special:StrainNewPage

**Comment by jimhu-tamu** [comment]
I just tested this and was able to create a page (which I deleted). I need more details about what was entered that did not work.

**Comment by KristenKC** [comment]
I ran into a problem when I was trying to create a page for Escherichia coli K-12 MG1655 lexA1 [Ind-] with OMP ! ST:159 as the parent strain 

Kristen Cunningham

**Comment by jimhu-tamu** [comment]
Try it changing the square brackets to parentheses.

TODO: filter forbidden characters from page names.
